CREATE TABLE coping_skill (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    child_skill TEXT NOT NULL,
    parent_skill TEXT NOT NULL,
    main_feeling INTEGER REFERENCES feelings(id)
);