DROP TABLE IF EXISTS coping_skill;
DROP TABLE IF EXISTS adv_feelings;
DROP TABLE IF EXISTS reminder;
DROP TABLE IF EXISTS identifier;
DROP TABLE IF EXISTS severity;
DROP TABLE IF EXISTS feelings;
DROP TABLE IF EXISTS user_type;
DROP TYPE IF EXISTS rating;
DROP TYPE IF EXISTS identifier_type;

CREATE TABLE user_type (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_type TEXT NOT NULL
);

CREATE TABLE feelings (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);

CREATE TABLE adv_feelings (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    main_feeling INTEGER REFERENCES feelings(id) NOT NULL
);

CREATE TYPE rating AS ENUM (
    'Low',
    'Medium',
    'High'
);

CREATE TABLE severity (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    level rating NOT NULL
);

CREATE TYPE identifier_type AS ENUM (
    'Feeling',
    'Severity'
);

CREATE TABLE identifier (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    identifier TEXT NOT NULL,
    type identifier_type NOT NULL
);

CREATE TABLE coping_skill (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    child_skill TEXT NOT NULL,
    parent_skill TEXT NOT NULL,
    main_feeling INTEGER REFERENCES feelings(id)
);

CREATE TABLE reminder (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reminder TEXT NOT NULL
);